language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

install:
  - "travis_retry pip install nose"
  - "travis_retry pip install coveralls"
  - "travis_retry pip install --pre -e .[testing]"

script: "python setup.py nosetests --with-coverage --cover-package=depot --cover-erase"

after_success:
  coveralls
