language: python
python:
  - "3.4"
  - "3.5"
  - "3.7"
  - "3.8"

install:
  - "travis_retry pip install -U pytest pytest-cov"
  - "travis_retry pip install coveralls"
  - "travis_retry pip install --pre -e .[testing]"

script: "pytest --cov=tgext.utils"

after_success:
  coveralls
